Experimental ws for H3Grafserv
benjie/crystal pull request #495
Opened 2023-08-31 14:03 UTC by Dodobibi

This PR add :
- bump to h3@1.8.1
- replace `getMethod` (deprecated in h3@1.8.1) with `event.method`
- `handleEvent`, `handleGraphiqlEvent` and `handleEventStreamEvent` helpers (for using with nuxt3)
- `addTo` to H3Grafserv (for using with h3 as standalone),
- add an experimental `H3Grafserv` (when importing via `server/h3/v1/experimental') for implements subsciption-ws for h3 (or nuxt3)

2023-09-02 08:17 UTC, Dodobibi commented
Yes,  It was just for making the new methods clearly experimental.
New commit rebased.

2023-09-02 08:24 UTC, benjie commented
Nice! From a quick scan this is looking really good (will do a better review later). Have you tested it well and are happy it works? Could you add a page to the documentation for it; it would be a `h3.md` file created here:

https://github.com/benjie/crystal/tree/main/grafast/website/grafserv/servers

Ideally you should document how to use it with a nuxt app ❤️

2023-09-02 08:49 UTC, Dodobibi commented
> Have you tested it well and are happy it works?

Yes, for h3 as a standalone server and for nuxt too.

> Could you add a page to the documentation for it

Yes, I will try to draft this, but you will have to (or @jemgillam) review my English syntax...

> Ideally you should document how to use it with a nuxt app

Of course.

2023-09-02 12:00 UTC, benjie commented
We tend to always edit the documentation whether the author is a native English speaker or not, so don't worry about that! Mostly I care about the instructions themselves, since I don't currently use Nuxt.

2023-09-06 14:52 UTC, peteromano commented
Hi guys! I know you're busy this week benjie, any chance of merging this this week?

If not, I'll pull the branch and work off/test that for now.

@Dodobibi fyi I'm also working on nuxt 3 integration. Can collab of the discord channel @peteromano 🙂

2023-09-12 03:11 UTC, peteromano commented
Yea it seemed to work yesterday, gonna spend some more time with it later this week, no rush.

2023-09-16 16:09 UTC, benjie requested changes
Looks good to me!

2023-09-16 16:09 UTC, benjie commented on grafast/grafserv/src/servers/h3/v1/index.ts
> +   * @deprecated use handleGraphqlEvent instead
```suggestion
   * @deprecated use handleGraphQLEvent instead
```

2023-09-16 16:09 UTC, benjie commented on grafast/grafserv/src/servers/h3/v1/index.ts
> +    return this.handleGraphqlEvent(event);
```suggestion
    return this.handleGraphQLEvent(event);
```

2023-09-16 16:09 UTC, benjie commented on grafast/grafserv/src/servers/h3/v1/index.ts
> +  public async handleGraphqlEvent(event: H3Event) {
```suggestion
  public async handleGraphQLEvent(event: H3Event) {
```

2023-09-16 16:09 UTC, benjie commented on grafast/grafserv/src/servers/h3/v1/index.ts
> +      eventHandler((event) => this.handleGraphqlEvent(event)),
```suggestion
      eventHandler((event) => this.handleGraphQLEvent(event)),
```

2023-09-16 16:10 UTC, benjie approved these changes

2023-09-16 17:47 UTC, merged